language: objective-c
osx_image: xcode7.3
# blacklist
branches:
  except:
    - auth
script:
- set -o pipefail
- xcodebuild -project BigBrother.xcodeproj -scheme BigBrother -sdk iphonesimulator9.0  test | xcpretty -c
- pod lib lint --quick
