language: objective-c
osx_image: beta-xcode6.3
# blacklist
branches:
  except:
    - auth
before_install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
- set -o pipefail
- xcodebuild -project BigBrother.xcodeproj -scheme BigBrother test -sdk iphonesimulator8.3 | xcpretty -c
- pod lib lint --quick
