language: objective-c
osx_image: xcode7
# blacklist
branches:
  except:
    - auth
script:
- set -o pipefail
- xcodebuild -project BigBrother.xcodeproj -scheme BigBrother test | xcpretty -c
- pod lib lint --quick
