language: objective-c
osx_image: xcode61
# blacklist
branches:
  except:
    - auth
before_install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
- set -o pipefail
- xcodebuild -project BigBrother.xcodeproj -scheme BigBrother test | xcpretty -c
- pod lib lint --quick
